### ISSUE TITLE
Sync auto-generated config values at cluster install

### ISSUE THREAD

**Issue by JKawohl** [owncloud-ansible/owncloud#19]
When installing ownCloud on several servers for one instance, 

we can save time by not running the full owncloud playbook against the replica nodes. 

One full blown installation should suffice, copying to the new instances should be quicker and less confusing. 

thanks @enbrnz

**Comment by JKawohl** [comment]
https://github.com/owncloud-ansible/owncloud/blob/08a5570849822b9d0b48d34ebd1f97c04b0111a6/tasks/setup.yml#L129

We could add an if condition for /installing/ upgrading. 

We should copy from primary node , when installation completed to replica nodes. Last step after turning off maintenance must be the copy to the replicas.

**Comment by JKawohl** [comment]
When utilizing a shared config folder, we can also skip the copy but will have to set up the shared storage.

**Comment by xoxys** [comment]
> When installing ownCloud on several servers for one instance,
> 
> we can save time by not running the full owncloud playbook against the replica nodes.
> 
> One full blown installation should suffice, copying to the new instances should be quicker and less confusing.

No, that's not the Ansible way. Copying files between hosts is an ugly workaround.

**Comment by enbrnz** [comment]
> No, that's not the Ansible way. Copying files between hosts is an ugly workaround.


I didn't mean copy in a sense of an actual copy command, I mean that we have to somehow set the instance-id and salt in the config.php on the replicas to the same values as the primary. This has to be done as the final step after primary has been fully set up.

**Comment by enbrnz** [comment]
https://github.com/owncloud-ansible/owncloud/issues/28
