### ISSUE TITLE
missing commands in the setup doc

### ISSUE THREAD

**Issue by voroyam** [owncloud-ansible/owncloud#49]
Always good to start with an updates system when installing something new, so I would add

`apt update` optionally `apt upgrade` to the top of the commands list on 
https://owncloud-ansible.github.io/getting_started/setup/#general

I ran in to the same issue that @jnweiger ran in to, the wheel issue. Had to search Chat to find out the solution.
Imho needs to be documented that you need:

`pip3 install wheel ansible` instead of just `pip3 install ansible`

**Comment by xoxys** [comment]
Where do you start and where do you stop. TBH `apt update` in front of an `apt install` should be common knowledge, otherwise I would suggest stopping using Ansible and learn some basics of your Linux OS of choice first.

Adding `wheel` as dependency might make sense.

**Comment by voroyam** [comment]
I expect from a documentation to give me the commands I need to get it running.

https://docs.docker.com/engine/install/ubuntu/

Docker docs even document that you have to remove previous docker installations before installing a new one, and they do have an `apt update` documented.

**Comment by xoxys** [comment]
Then we have different opinions.

**Comment by jnweiger** [comment]
Neither works well, afaik. My opinion:
* Start the document by naming the target audience: "This chapter asumes you are familiar with debian package management and X, Y. Z"
* Then the commands focus only on what goes beyond that list.

(Opinion only, the decision belongs to the documentation team, of course)

**Comment by xoxys** [comment]
Its a dev documentation in the same way as owncloud.dev is, so we are responsible on our own.

**Comment by xoxys** [comment]
`wheel` package added. The pip instruction will stay as it is to be OS independent.

**Comment by voroyam** [comment]
Thanks for improving the docs. 

Is there a difference between installing Ansible via pip or with the repository on Ubuntu?

I installed it via Pip, because at the time there was no other way, and I noticed in the other Ansible tutorials there is a directory created at /etc/ansible with roles, config and hosts, and I am missing that.

**Comment by xoxys** [comment]
I dont know what they ship with OS packages, never used it.
