### ISSUE TITLE
Add option to deploy static single purpose configs

### ISSUE THREAD

**Issue by JKawohl** [owncloud-ansible/owncloud#5]
Use Case:  
I have a fuctioning LDAP configuration and want to migrate my data and users. 

For that i would like to be able to deploy e.g. a ldap.config.php along the config.php and user.config.php

**Comment by enbrnz** [comment]
It is already possible to configure LDAP through ansible.
I don't think it is necessary to increase the complexity playbook itself to enable split config files. However I think we should provide more examples on how to configure specific apps in our documentation, like for example LDAP.
